// <auto-generated />
using AprendeNetCore2.DataAccess.DBModelsUpdate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AprendeNetCore2.Migrations
{
    [DbContext(typeof(aprendeprogramarContext))]
    partial class aprendeprogramarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AprendeNetCore2.DBModelsUpdate.Empresas", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("City")
                        .HasColumnType("ntext");

                    b.Property<string>("Ejemplo");

                    b.Property<string>("Name")
                        .HasColumnType("ntext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("ntext");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AprendeNetCore2.DBModelsUpdate.Users", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Age");

                    b.Property<string>("City");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Surname")
                        .HasColumnType("ntext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
